GeometricProgramming/Models/PrintModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GeometricProgramming.Models
{
    public class PrintModel
    {
    }
}

GeometricProgramming/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using GeometricProgramming.Services.Abstract;

namespace GeometricProgramming.Controllers
{
    public class HomeController : Controller
    {
        private readonly IPrintService _printService;
        public HomeController(IPrintService printService)
        {
            this._printService = printService;
        }
        public IActionResult Index()
        {
            return View();
        }       
        
    }
}

GeometricProgramming/Controllers/ImagingController.cs
namespace GeometricProgramming
{
    using Microsoft.AspNetCore.Mvc;
    using System;
    using System.Collections.Generic;
    using GeometricProgramming.Common.Models;
    using GeometricProgramming.Services.Abstract;

    [Route("api/[controller]/[action]")]
    [ApiController]
    public class ImagingController : ControllerBase
    {
        private readonly IPrintService _printService;
        public ImagingController(IPrintService printService)
        {
            this._printService = printService;
        }

        [HttpPost]
        [ActionName("PrintAllTrianglesInBox")]
        public IActionResult PrintAllTrianglesInBox([FromBody] GeometryDto geometryDto)
        {
            try
            {
                var result = _printService.PlotAllTriangles(new ImagingDto { Columns = geometryDto.Columns, Rows = geometryDto.Rows, PixelSize = geometryDto.PixelSize, Triangles = new List<TriangleDto>() });
                return File(result.MainImage, "image/jpeg");
            }
            catch (Exception ex)
            {
                return Problem(ex.Message);
            }
        }

        [HttpPost]
        [ActionName("PrintGivenTriangles")]
        public IActionResult PrintGivenTriangles([FromBody] ImagingDto imagingDto)
        {
            try
            {
                var result = _printService.PlotGivenTriangles(imagingDto);
                return File(result.MainImage, "image/jpeg");
            }
            catch (Exception ex)
            {
                return Problem(ex.Message);
            }
        }

        [HttpPost]
        [ActionName("EvaluateTrianglesPositions")]
        public IActionResult EvaluateTrianglesPositions([FromBody] ImagingDto imagingDto)
        {
            try
            {
                var result = _printService.GetTrianglesPositions(imagingDto);
                return Ok(result.Result);
            }
            catch (Exception ex)
            {
                return Problem(ex.Message);
            }
        }

        [HttpPost]
        [ActionName("EvluateTriangleCoordinates")]
        public IActionResult EvluateTriangleCoordinates([FromBody] GeometryDto geometryDto)
        {
            try
            {
                var result = _printService.GetTriangleCoordinates(geometryDto);
                return Ok(result);
            }
            catch (Exception ex)
            {
                return Problem(ex.Message);
            }
        }

    }
}

GeometricProgramming/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<p>
    <div>
        <h3>Welcome to Geometric Plotting</h3>
        <br />
        <img src="@Url.Action("GetAllTriangles","Imaging")" title="Triangle with 6 rows and 6 columns plotted within 300 pixel box." />
    </div>
</p>

GeometricProgramming/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GeometricProgramming</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>   
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
   
</body>
</html>